# Generated by Django 5.0.2 on 2024-03-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_remove_recorder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='name',
            field=models.CharField(default='untitled', max_length=255),
            preserve_default=False,
        ),
    ]
