# Generated by Django 5.0.2 on 2024-03-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0003_recorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='transcribed_text',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
