# Generated by Django 5.0.2 on 2024-03-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0004_recorder_transcribed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='corrected_sentence',
            field=models.TextField(default='NO'),
            preserve_default=False,
        ),
    ]
