# Generated by Django 5.0 on 2024-03-05 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0005_recorder_corrected_sentence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorder',
            name='name',
        ),
        migrations.AddField(
            model_name='recorder',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordlist', models.TextField()),
                ('unique_wordlist', models.TextField()),
                ('extracted_idioms', models.TextField()),
                ('a1_list', models.TextField()),
                ('a2_list', models.TextField()),
                ('b1_list', models.TextField()),
                ('b2_list', models.TextField()),
                ('c1_list', models.TextField()),
                ('c2_list', models.TextField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorder.recorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
